// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import broker "github.com/scraly/go.common/pkg/broker"
import mock "github.com/stretchr/testify/mock"

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// Options provides a mock function with given fields:
func (_m *Subscriber) Options() broker.SubscribeOptions {
	ret := _m.Called()

	var r0 broker.SubscribeOptions
	if rf, ok := ret.Get(0).(func() broker.SubscribeOptions); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(broker.SubscribeOptions)
	}

	return r0
}

// Topic provides a mock function with given fields:
func (_m *Subscriber) Topic() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields:
func (_m *Subscriber) Unsubscribe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
